url: "http://dannywhite.site" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/ephemera" # the subpath of your site, e.g. /blog
title: "Ephemera" # the name of your site, e.g. ACME Corp.
